In [1]:
#here we just classify the data whether the patient has worsening of the OA after the 6th visit

import pandas as pd

df = pd.read_excel("KL.xlsx",header = None, names = ['ID','SIDE','V00XRKL','V01XRKL','V03XRKL','V05XRKL','V06XRKL','V08XRKL','V10XRKL'])

In [2]:
df

,ID,SIDE,V00XRKL,V01XRKL,V03XRKL,V05XRKL,V06XRKL,V08XRKL,V10XRKL
0,9000099,1,2.0,2.0,2.0,2.0,2.0,NaN,NaN
1,9000099,2,3.0,4.0,4.0,4.0,4.0,NaN,NaN
2,9000296,1,2.0,2.0,NaN,2.0,2.0,NaN,NaN
3,9000296,2,3.0,3.0,NaN,3.0,3.0,NaN,NaN
4,9000622,1,1.0,1.0,NaN,NaN,NaN,NaN,NaN
5,9000622,2,1.0,1.0,NaN,NaN,NaN,NaN,NaN
6,9000798,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
7,9000798,2,4.0,4.0,4.0,4.0,4.0,NaN,NaN
8,9001104,1,3.0,3.0,NaN,NaN,NaN,NaN,NaN
9,9001104,2,1.0,1.0,NaN,NaN,NaN,NaN,NaN
10,9001400,1,1.0,1.0,1.0,1.0,NaN,NaN,NaN
11,9001400,2,1.0,1.0,1.0,1.0,NaN,NaN,NaN
12,9001695,1,2.0,2.0,2.0,NaN,3.0,NaN,NaN
13,9001695,2,0.0,0.0,0.0,NaN,0.0,0.0,NaN
14,9001897,1,3.0,3.0,3.0,3.0,3.0,NaN,NaN
15,9001897,2,0.0,0.0,0.0,0.0,1.0,1.0,2.0
16,9002116,1,2.0,2.0,2.0,2.0,3.0,NaN,NaN
17,9002116,2,3.0,3.0,4.0,4.0,4.0,NaN,NaN
18,9002316,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
19,9002316,2,1.0,2.0,2.0,2.0,2.0,NaN,NaN
20,9002411,1,2.0,2.0,2.0,2.0,NaN,NaN,NaN
21,9002411,2,2.0,2.0,2.0,2.0,NaN,NaN,NaN
22,9002430,1,2.0,2.0,2.0,2.0,3.0,NaN,NaN
23,9002430,2,3.0,3.0,3.0,3.0,3.0,NaN,NaN
24,9002817,1,3.0,3.0,3.0,3.0,3.0,NaN,NaN
25,9002817,2,2.0,2.0,2.0,2.0,2.0,NaN,NaN
26,9003126,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,9003126,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,9003175,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,9003175,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...
8952,9996851,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0
8953,9996851,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8954,9996865,1,3.0,3.0,3.0,3.0,3.0,NaN,NaN
8955,9996865,2,4.0,4.0,4.0,4.0,4.0,NaN,NaN
8956,9997042,1,2.0,NaN,2.0,2.0,NaN,NaN,NaN
8957,9997042,2,2.0,NaN,2.0,2.0,NaN,NaN,NaN
8958,9997381,1,2.0,2.0,2.0,2.0,2.0,NaN,NaN
8959,9997381,2,2.0,2.0,2.0,2.0,2.0,NaN,NaN
8960,9997610,1,2.0,2.0,2.0,2.0,2.0,NaN,NaN
8961,9997610,2,0.0,0.0,0.0,0.0,0.0,NaN,NaN
8962,9997856,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8963,9997856,2,4.0,4.0,4.0,4.0,4.0,NaN,NaN
8964,9997869,1,2.0,2.0,2.0,2.0,2.0,NaN,NaN
8965,9997869,2,0.0,0.0,0.0,0.0,0.0,NaN,NaN
8966,9998089,1,2.0,2.0,2.0,2.0,2.0,NaN,NaN
8967,9998089,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0
8968,9998384,1,3.0,3.0,3.0,4.0,4.0,NaN,NaN
8969,9998384,2,2.0,2.0,2.0,2.0,2.0,NaN,NaN
8970,9999295,1,2.0,2.0,2.0,2.0,2.0,NaN,NaN
8971,9999295,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8972,9999365,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0
8973,9999365,2,0.0,0.0,0.0,0.0,0.0,NaN,4.0
8974,9999510,1,1.0,1.0,1.0,1.0,1.0,2.0,3.0
8975,9999510,2,3.0,3.0,3.0,3.0,3.0,NaN,NaN
8976,9999862,1,2.0,3.0,3.0,3.0,NaN,NaN,NaN
8977,9999862,2,2.0,2.0,2.0,2.0,NaN,NaN,NaN
8978,9999865,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0
8979,9999865,2,1.0,1.0,1.0,1.0,1.0,NaN,2.0
8980,9999878,1,2.0,2.0,NaN,2.0,2.0,NaN,NaN
8981,9999878,2,1.0,1.0,NaN,1.0,1.0,1.0,1.0

In [3]:
df = df.dropna(subset=['V06XRKL'])
df = df.dropna(subset=['V08XRKL','V10XRKL'], how='all')

df

,ID,SIDE,V00XRKL,V01XRKL,V03XRKL,V05XRKL,V06XRKL,V08XRKL,V10XRKL
6,9000798,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
13,9001695,2,0.0,0.0,0.0,NaN,0.0,0.0,NaN
15,9001897,2,0.0,0.0,0.0,0.0,1.0,1.0,2.0
18,9002316,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0
26,9003126,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,9003126,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,9003175,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,9003175,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0
31,9003316,2,0.0,0.0,0.0,0.0,0.0,NaN,0.0
33,9003380,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0
40,9003815,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,9003815,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,9004175,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0
46,9004184,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,9004184,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0
50,9004669,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,9004669,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,9005321,1,0.0,0.0,0.0,0.0,0.0,2.0,2.0
59,9005321,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60,9005413,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,9005413,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,9006140,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,9006140,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,9006407,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
68,9006723,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0
74,9008322,1,1.0,1.0,NaN,1.0,1.0,2.0,2.0
78,9008820,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,9008820,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0
82,9008934,1,1.0,1.0,1.0,1.0,1.0,1.0,3.0
83,9008934,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...
8889,9988921,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8892,9989352,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8893,9989352,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0
8895,9989700,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8900,9990355,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8901,9990355,2,0.0,0.0,0.0,0.0,0.0,2.0,2.0
8908,9991580,1,1.0,2.0,1.0,1.0,2.0,2.0,2.0
8915,9992756,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0
8920,9993362,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8921,9993362,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8926,9993833,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN
8930,9994363,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0
8931,9994363,2,1.0,1.0,1.0,1.0,1.0,NaN,1.0
8938,9995338,1,0.0,0.0,0.0,2.0,2.0,2.0,2.0
8942,9995913,1,1.0,1.0,NaN,1.0,1.0,1.0,NaN
8944,9996086,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8945,9996086,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8948,9996284,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8949,9996284,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8952,9996851,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0
8953,9996851,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8962,9997856,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8967,9998089,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0
8971,9999295,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8972,9999365,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0
8973,9999365,2,0.0,0.0,0.0,0.0,0.0,NaN,4.0
8974,9999510,1,1.0,1.0,1.0,1.0,1.0,2.0,3.0
8978,9999865,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0
8979,9999865,2,1.0,1.0,1.0,1.0,1.0,NaN,2.0
8981,9999878,2,1.0,1.0,NaN,1.0,1.0,1.0,1.0

In [4]:
df['diff68'] = df['V08XRKL'] - df['V06XRKL']
df['diff610'] = df['V10XRKL'] - df['V06XRKL']

df

,ID,SIDE,V00XRKL,V01XRKL,V03XRKL,V05XRKL,V06XRKL,V08XRKL,V10XRKL,diff68,diff610
6,9000798,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
13,9001695,2,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN
15,9001897,2,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0
18,9002316,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
26,9003126,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,9003126,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,9003175,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,9003175,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
31,9003316,2,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0
33,9003380,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
40,9003815,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,9003815,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,9004175,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
46,9004184,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,9004184,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
50,9004669,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,9004669,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,9005321,1,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0
59,9005321,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60,9005413,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,9005413,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,9006140,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,9006140,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,9006407,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
68,9006723,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0
74,9008322,1,1.0,1.0,NaN,1.0,1.0,2.0,2.0,1.0,1.0
78,9008820,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,9008820,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
82,9008934,1,1.0,1.0,1.0,1.0,1.0,1.0,3.0,0.0,2.0
83,9008934,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
8889,9988921,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8892,9989352,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8893,9989352,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
8895,9989700,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8900,9990355,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8901,9990355,2,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0
8908,9991580,1,1.0,2.0,1.0,1.0,2.0,2.0,2.0,0.0,0.0
8915,9992756,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
8920,9993362,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8921,9993362,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8926,9993833,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,0.0,NaN
8930,9994363,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0
8931,9994363,2,1.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,0.0
8938,9995338,1,0.0,0.0,0.0,2.0,2.0,2.0,2.0,0.0,0.0
8942,9995913,1,1.0,1.0,NaN,1.0,1.0,1.0,NaN,0.0,NaN
8944,9996086,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8945,9996086,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8948,9996284,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8949,9996284,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8952,9996851,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
8953,9996851,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8962,9997856,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8967,9998089,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
8971,9999295,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8972,9999365,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0
8973,9999365,2,0.0,0.0,0.0,0.0,0.0,NaN,4.0,NaN,4.0
8974,9999510,1,1.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,2.0
8978,9999865,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0
8979,9999865,2,1.0,1.0,1.0,1.0,1.0,NaN,2.0,NaN,1.0
8981,9999878,2,1.0,1.0,NaN,1.0,1.0,1.0,1.0,0.0,0.0

In [5]:
df['diff'] = df[['diff68', 'diff610']].max(axis=1)
df

,ID,SIDE,V00XRKL,V01XRKL,V03XRKL,V05XRKL,V06XRKL,V08XRKL,V10XRKL,diff68,diff610,diff
6,9000798,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
13,9001695,2,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0
15,9001897,2,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,1.0
18,9002316,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
26,9003126,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,9003126,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,9003175,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,9003175,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
31,9003316,2,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0
33,9003380,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
40,9003815,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,9003815,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,9004175,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
46,9004184,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,9004184,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
50,9004669,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,9004669,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,9005321,1,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
59,9005321,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60,9005413,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,9005413,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,9006140,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,9006140,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67,9006407,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
68,9006723,1,1.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0
74,9008322,1,1.0,1.0,NaN,1.0,1.0,2.0,2.0,1.0,1.0,1.0
78,9008820,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,9008820,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
82,9008934,1,1.0,1.0,1.0,1.0,1.0,1.0,3.0,0.0,2.0,2.0
83,9008934,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8889,9988921,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8892,9989352,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8893,9989352,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
8895,9989700,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8900,9990355,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8901,9990355,2,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0
8908,9991580,1,1.0,2.0,1.0,1.0,2.0,2.0,2.0,0.0,0.0,0.0
8915,9992756,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
8920,9993362,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8921,9993362,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8926,9993833,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,0.0,NaN,0.0
8930,9994363,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0
8931,9994363,2,1.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,0.0,0.0
8938,9995338,1,0.0,0.0,0.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0
8942,9995913,1,1.0,1.0,NaN,1.0,1.0,1.0,NaN,0.0,NaN,0.0
8944,9996086,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8945,9996086,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8948,9996284,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8949,9996284,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8952,9996851,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
8953,9996851,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8962,9997856,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8967,9998089,2,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
8971,9999295,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8972,9999365,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0
8973,9999365,2,0.0,0.0,0.0,0.0,0.0,NaN,4.0,NaN,4.0,4.0
8974,9999510,1,1.0,1.0,1.0,1.0,1.0,2.0,3.0,1.0,2.0,2.0
8978,9999865,1,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0
8979,9999865,2,1.0,1.0,1.0,1.0,1.0,NaN,2.0,NaN,1.0,1.0
8981,9999878,2,1.0,1.0,NaN,1.0,1.0,1.0,1.0,0.0,0.0,0.0

In [6]:
df['target'] = (df['diff']>0.0) #these are the unhealthy patients
df['target'] = df['target'].astype(int)
df.drop(['SIDE','V00XRKL','V01XRKL','V03XRKL','V05XRKL','V06XRKL','V08XRKL','V10XRKL','diff68','diff610','diff'],axis=1,inplace=True)

df

           ID  target
6     9000798       0
13    9001695       0
15    9001897       1
18    9002316       0
26    9003126       0
27    9003126       0
28    9003175       0
29    9003175       1
31    9003316       0
33    9003380       0
40    9003815       0
41    9003815       0
45    9004175       0
46    9004184       0
47    9004184       0
50    9004669       0
51    9004669       0
58    9005321       1
59    9005321       0
60    9005413       0
61    9005413       0
64    9006140       0
65    9006140       0
67    9006407       0
68    9006723       0
74    9008322       1
78    9008820       0
79    9008820       1
82    9008934       1
83    9008934       0
...       ...     ...
8889  9988921       0
8892  9989352       0
8893  9989352       0
8895  9989700       0
8900  9990355       0
8901  9990355       1
8908  9991580       0
8915  9992756       0
8920  9993362       0
8921  9993362       0
8926  9993833       0
8930  9994363       0
8931  9994363       0
8938  9995338       0
8942  9995913       0
8944  9996086       0
8945  9996086       0
8948  9996284       0
8949  9996284       0
8952  9996851       1
8953  9996851       0
8962  9997856       0
8967  9998089       1
8971  9999295       0
8972  9999365       0
8973  9999365       1
8974  9999510       1
8978  9999865       0
8979  9999865       1
8981  9999878       0

[3165 rows x 2 columns]

In [7]:
df = df.groupby('ID').max().reset_index()

In [8]:
df.to_csv('target.csv')

In [9]:
df

           ID  target
0     9000798       0
1     9001695       0
2     9001897       1
3     9002316       0
4     9003126       0
5     9003175       1
6     9003316       0
7     9003380       0
8     9003815       0
9     9004175       0
10    9004184       0
11    9004669       0
12    9005321       1
13    9005413       0
14    9006140       0
15    9006407       0
16    9006723       0
17    9008322       1
18    9008820       1
19    9008934       1
20    9009927       0
21    9010060       0
22    9010308       0
23    9010370       0
24    9010952       0
25    9011115       0
26    9011641       0
27    9011949       1
28    9012435       0
29    9013634       0
...       ...     ...
1931  9979181       0
1932  9979306       0
1933  9980274       0
1934  9980704       0
1935  9980752       0
1936  9982186       0
1937  9983246       0
1938  9985803       0
1939  9986838       0
1940  9988921       0
1941  9989352       0
1942  9989700       0
1943  9990355       1
1944  9991580       0
1945  9992756       0
1946  9993362       0
1947  9993833       0
1948  9994363       0
1949  9995338       0
1950  9995913       0
1951  9996086       0
1952  9996284       0
1953  9996851       1
1954  9997856       0
1955  9998089       1
1956  9999295       0
1957  9999365       1
1958  9999510       1
1959  9999865       1
1960  9999878       0

[1961 rows x 2 columns]